### ISSUE TITLE
Add rate limit handling

### ISSUE THREAD

**Issue by tommoor** [goabstract/abstract-sdk#56] opened 2018-12-18 19:12 UTC
I'd suggest the following but am of course open to other things:

- First pass: Add a custom error that is thrown when the rate limit is hit
- Second pass: Internally handle the rate limit and wait for the appropriate amount of time based on the response headers before continuing.

**Comment by bitpshr** [comment] 2019-01-24 16:52
Thinking about this more, do we really want to internally handle the rate limit by caching requests and firing them once enough time has passed? This feels like non-obvious behavior that may open up our APIs to maxed-out per-token usage and ever-growing response times, potentially unknowingly to the downstream user.

Example:

A user could execute some logic many times a second resulting in ~80 requests per second. The first 60 requests are resolved on-time, whereas the remaining 20 are cached, fired, and resolved when enough milliseconds pass to free up the user's rate limits. The user is none-the-wiser and thinks all 80 requests successfully resolved on-time. This means that the user can only execute 40 more requests in the current second, so on the next interval of their logic, 40 requests are resolved on-time and 40 requests are cached for the next rate limit turn. This cycle repeats indefinitely, and a user's requests would appear to take longer and longer with no indication as to why.

**Comment by amccloud** [comment] 2019-01-24 17:15
@bitpshr yea we wouldn't want to suppress notice of a rate limit just because there have a cache. But it would be nice to get a cache in so hitting the rate limit would be less likely (e.g. resolving "latest" can be expensive)

We still should think through how backoff/retry will work but I think that can be during the second pass. My hunch here is we are going to want to force applications to handle this because of the lengthy backoff duration, so throwing a custom error would be ideal (maybe for 500, 403 and 404 too?)

**Comment by tommoor** [comment] 2019-01-25 11:20
Agree, your logic makes sense.

**Closed** 2019-01-26 16:06 UTC
Labels: enhancement

**Comment by szimek** [comment] 2019-02-11 20:39
We're currently investigating using abstract-sdk to fetch screenshots of our components (using `abstract.previews.raw` call) that would then be used on our internal design system page, so that we can easily keep them up to date.

The issue is that during my tests I'm hitting the rate limit quite often and I suppose that with an empty cache (e.g. after deploying a new version of this script) I'd also hit it pretty fast. For now I've just added a delay between every `abstract.previews.raw` call and it seems to work fine, but obviously it's not reliable or optimal.

E.g. Contentful SDK [handles rate limit internally](https://github.com/contentful/contentful-sdk-core/blob/master/lib/rate-limit.js) and reports a warning `Rate limit error occurred. Waiting for ${wait} ms before retrying...`, which could be enough to let user know that something is wrong in the scenario described by @bitpshr.

**Comment by bitpshr** [comment] 2019-02-13 13:13
Hi @szimek, thanks for the added context around your rate-limited SDK usage so far. Feedback like this is extremely helpful. We're definitely still investigating the best way to handle rate limits and hope to improve this experience in coming releases.

For now, when interacting with the Abstract SDK and a `RateLimitError` is thrown, the error itself contains useful information that helps developers reliably know when to safely make requests again. There's an epoch timestamp exposed at `RateLimitError.data.resetsAt` indicating the number of milliseconds until the rate limit resets.

Using this, you can already use the SDK safely within the confines of our defined rate limits without guessing at an arbitrary timeout between calls:

```js
import * as Abstract from "abstract";

// Create a client
const abstract = Abstract.Client({ /* ... */ });

// Write previews every 10 seconds
const defaultTimeout = 10000;

// Write the previews
async function writePreviews() {
	let timeout = defaultTimeout;
	try {
		const collection = await abstract.collections.info({ /* ... */ });
		const layer = collection.layers[0];
		const buffer = await abstract.previews.raw({ /* ... */ });
		fs.writeFile("preview.png", Buffer.from(buffer));
	} catch (error) {
		// Catch RateLimitError instances
		if (error instanceof Abstract.errors.RateLimitError) {
			// Use the resetsAt error data
			timeout = error.data.resetsAt;
		}
	}

	setTimeout(writePreviews, timeout);
}

// Kick things off
writePreviews();
```

The code above demonstrates one way to call the SDK on any desired interval, while still using the information exposed on thrown rate limit errors to safely resume requests if needed.

There's still more we're researching. For reference, Abstract uses a 1-minute rate limit interval whereas something like Contentful uses a 1-second interval; this allows the Contentful SDK to queue rate limit failures and auto-retry them quickly without the user ever knowing. If we did that with our current 1-minute interval, Abstract SDK consumers could be waiting ~60 seconds for their queued request to ultimately be retried. Still, there's more we're looking into, such as increasing our rate limit or decreasing its interval.

Thanks again for the added context.

**Comment by bitpshr** [comment] 2019-02-13 17:59
Hi @szimek, thanks for the added context around your rate-limited SDK usage so far. Feedback like this is extremely helpful. We're definitely still investigating the best way to handle rate limits and hope to improve this experience in coming releases.

For now, when interacting with the Abstract SDK and a `RateLimitError` is thrown, the error itself contains useful information that helps developers reliably know when to safely make requests again. There's an epoch timestamp exposed at `RateLimitError.data.resetsAt` indicating the number of milliseconds until the rate limit resets.

Using this, you can already use the SDK safely within the confines of our defined rate limits without random timeouts:

```js
import * as Abstract from "abstract";

// Create a client
const abstract = Abstract.Client({ /* ... */ });

// Write previews every 10 seconds
const defaultTimeout = 10000;

// Write the previews
async function writePreviews() {
	let timeout = defaultTimeout;
	try {
		const collection = await abstract.collections.info({ /* ... */ });
		const layer = collection.layers[0];
		const buffer = await abstract.previews.raw({ /* ... */ });
		fs.writeFile("preview.png", Buffer.from(buffer));
	} catch (error) {
		// Catch RateLimitError instances
		if (error instanceof Abstract.errors.RateLimitError) {
			// Use the resetsAt error data
			timeout = error.data.resetsAt;
		}
	}

	setTimeout(writePreviews, timeout);
}

// Kick things off
writePreviews();
```

The code above demonstrates one way to call the SDK on any desired interval, while still using the information exposed on thrown rate limit errors to safely resume requests if needed.

There's definitely still more we're researching. For reference, Abstract uses a 1-minute rate limit interval whereas something like Contentful uses a 1-second interval; this allows the Contentful SDK to queue rate limit failures and auto-retry them quickly without the user ever knowing. If we did that with our current 1-minute interval, Abstract SDK consumers could be waiting ~60 seconds for their queued request to ultimately be retried. Still, there's more we're looking into, such as increasing our rate limit or decreasing its interval.

Thanks again for the added context, this will help us prioritize more graceful rate limit handling.
