### ISSUE TITLE
Enable CORS for Previews API endpoints

### ISSUE THREAD

**Issue by erlswtshrt** [goabstract/abstract-sdk#315] opened 2020-10-26 21:49 UTC
Hi there, I've noticed that CORS has been opened up on `api.goabstract...` but not on `previews.api...` Any chance we can enable it for the previews API? Thanks!

**Comment by tommoor** [comment] 2020-11-14 00:31
Looking into this for you, sorry for the delay

**Comment by tommoor** [comment] 2020-11-16 20:24
We're working on this internally now, someone will update here and close the issue once CORS is enabled.

**Comment by tommoor** [comment] 2020-11-20 19:10
Hi, CORS has now been opened up on these endpoints.

**Comment by erlswtshrt** [comment] 2020-11-24 17:29
Hey @tommoor, thanks for your help with this! Unfortunately, I'm still getting a CORS error when hitting these endpoints (`client.previews.raw({...})`). Is there anything I need to update on my end? Thx again.

**Comment by erlswtshrt** [comment] 2021-01-04 16:50
Hey @tommoor just wanted to check in on this. Any idea why I might still be running into CORS issues with these endpoints? Thanks!

**Comment by deaththeeny** [comment] 2021-01-09 19:43
Hello! I have the same problem. I tried to reach the previews.api with localhost. But it works with postman.

**Comment by kirupa** [comment] 2021-01-19 19:21
Hi @tommoor - just wanted to follow-up on this. We are blocked on our end without this change, so please let us know if there is something we need to do differently to avoid the CORS error.

Thanks,
Kirupa (SLDS PM)

**Comment by tylermarshall** [comment] 2021-01-22 17:19
Sorry for the delay on this issue. We had CORS configured previously, but it was a bit more restrictive than we intended. We've since adjusted the policy and validated the endpoints are now working as intended with CORS enabled. If you can validate on your end that would be great.

**Comment by tommoor** [comment] 2021-01-22 17:28
closing as complete, thanks for reporting everyone

**Closed by tommoor** 2021-01-22 17:28 UTC
Labels: enhancement

**Comment by deaththeeny** [comment] 2021-01-24 09:46
Thanks! For me it works now! 

Best, Denise

**Comment by erlswtshrt** [comment] 2021-01-25 19:06
Same here. Thanks!
